// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/chapters.dart';
import 'api/downloads.dart';
import 'api/episodes.dart';
import 'api/library.dart';
import 'api/models.dart';
import 'api/search.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 441877074;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'inktoon',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<BgDownloadProgress> crateApiModelsBgDownloadProgressDefault();

  Future<void> crateApiDownloadsCancelBackgroundDownload();

  Future<void> crateApiSimpleCancelBackgroundDownload();

  Future<void> crateApiLibraryDeleteChapter({
    required String basePath,
    required String webtoonId,
    required int chapterNumber,
  });

  Future<void> crateApiSimpleDeleteChapter({
    required String basePath,
    required String webtoonId,
    required int chapterNumber,
  });

  Future<void> crateApiLibraryDeleteWebtoon({
    required String basePath,
    required String webtoonId,
  });

  Future<void> crateApiSimpleDeleteWebtoon({
    required String basePath,
    required String webtoonId,
  });

  Future<CbzMetadata> crateApiDownloadsDownloadChapterAsCbz({
    required String basePath,
    required String webtoonId,
    required String webtoonTitle,
    required String chapterUrl,
    required int chapterNumber,
    required String chapterTitle,
  });

  Future<CbzMetadata> crateApiSimpleDownloadChapterAsCbz({
    required String basePath,
    required String webtoonId,
    required String webtoonTitle,
    required String chapterUrl,
    required int chapterNumber,
    required String chapterTitle,
  });

  Future<List<Uint8List>> crateApiDownloadsDownloadChapterImages({
    required String url,
  });

  Future<List<Uint8List>> crateApiSimpleDownloadChapterImages({
    required String url,
  });

  Future<Uint8List> crateApiDownloadsDownloadImage({required String imageUrl});

  Future<Uint8List> crateApiSimpleDownloadImage({required String imageUrl});

  Future<List<ChapterPage>> crateApiChaptersGetChapterPages({
    required String chapUrl,
  });

  Future<List<ChapterPage>> crateApiSimpleGetChapterPages({
    required String chapUrl,
  });

  Future<LibraryInfo> crateApiLibraryGetLibrary({required String basePath});

  Future<LibraryInfo> crateApiSimpleGetLibrary({required String basePath});

  Future<List<ApiEpisodeItem>> crateApiEpisodesGetWebtoonEpisodes({
    required String titleNo,
  });

  Future<List<ApiEpisodeItem>> crateApiSimpleGetWebtoonEpisodes({
    required String titleNo,
  });

  Future<WebtoonLibraryItem> crateApiLibraryGetWebtoonLibrary({
    required String basePath,
    required String webtoonId,
  });

  Future<WebtoonLibraryItem> crateApiSimpleGetWebtoonLibrary({
    required String basePath,
    required String webtoonId,
  });

  Future<String> crateApiDownloadsMergeCbzFiles({
    required String basePath,
    required String webtoonId,
    required String webtoonTitle,
    required List<int> chapterNumbers,
    required String outputName,
  });

  Future<String> crateApiSimpleMergeCbzFiles({
    required String basePath,
    required String webtoonId,
    required String webtoonTitle,
    required List<int> chapterNumbers,
    required String outputName,
  });

  Future<BgDownloadProgress> crateApiDownloadsPollDownloadProgress();

  Future<BgDownloadProgress> crateApiSimplePollDownloadProgress();

  Future<String> crateApiLibrarySaveWebtoonCover({
    required String basePath,
    required String webtoonId,
    required String coverUrl,
  });

  Future<String> crateApiSimpleSaveWebtoonCover({
    required String basePath,
    required String webtoonId,
    required String coverUrl,
  });

  Future<List<WebtoonResult>> crateApiSearchSearchWebtoons({
    required String keyword,
    required String langage,
  });

  Future<List<WebtoonResult>> crateApiSimpleSearchWebtoons({
    required String keyword,
    required String langage,
  });

  Future<void> crateApiDownloadsStartBackgroundDownload({
    required String basePath,
    required String webtoonId,
    required String webtoonTitle,
    required List<BgChapterTask> chapters,
  });

  Future<void> crateApiSimpleStartBackgroundDownload({
    required String basePath,
    required String webtoonId,
    required String webtoonTitle,
    required List<BgChapterTask> chapters,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BgDownloadProgress> crateApiModelsBgDownloadProgressDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bg_download_progress,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsBgDownloadProgressDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsBgDownloadProgressDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "bg_download_progress_default",
        argNames: [],
      );

  @override
  Future<void> crateApiDownloadsCancelBackgroundDownload() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDownloadsCancelBackgroundDownloadConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadsCancelBackgroundDownloadConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_background_download",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleCancelBackgroundDownload() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCancelBackgroundDownloadConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCancelBackgroundDownloadConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_background_download",
        argNames: [],
      );

  @override
  Future<void> crateApiLibraryDeleteChapter({
    required String basePath,
    required String webtoonId,
    required int chapterNumber,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          sse_encode_String(webtoonId, serializer);
          sse_encode_i_32(chapterNumber, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLibraryDeleteChapterConstMeta,
        argValues: [basePath, webtoonId, chapterNumber],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryDeleteChapterConstMeta =>
      const TaskConstMeta(
        debugName: "delete_chapter",
        argNames: ["basePath", "webtoonId", "chapterNumber"],
      );

  @override
  Future<void> crateApiSimpleDeleteChapter({
    required String basePath,
    required String webtoonId,
    required int chapterNumber,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          sse_encode_String(webtoonId, serializer);
          sse_encode_i_32(chapterNumber, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDeleteChapterConstMeta,
        argValues: [basePath, webtoonId, chapterNumber],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDeleteChapterConstMeta =>
      const TaskConstMeta(
        debugName: "delete_chapter",
        argNames: ["basePath", "webtoonId", "chapterNumber"],
      );

  @override
  Future<void> crateApiLibraryDeleteWebtoon({
    required String basePath,
    required String webtoonId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          sse_encode_String(webtoonId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLibraryDeleteWebtoonConstMeta,
        argValues: [basePath, webtoonId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryDeleteWebtoonConstMeta =>
      const TaskConstMeta(
        debugName: "delete_webtoon",
        argNames: ["basePath", "webtoonId"],
      );

  @override
  Future<void> crateApiSimpleDeleteWebtoon({
    required String basePath,
    required String webtoonId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          sse_encode_String(webtoonId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDeleteWebtoonConstMeta,
        argValues: [basePath, webtoonId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDeleteWebtoonConstMeta =>
      const TaskConstMeta(
        debugName: "delete_webtoon",
        argNames: ["basePath", "webtoonId"],
      );

  @override
  Future<CbzMetadata> crateApiDownloadsDownloadChapterAsCbz({
    required String basePath,
    required String webtoonId,
    required String webtoonTitle,
    required String chapterUrl,
    required int chapterNumber,
    required String chapterTitle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          sse_encode_String(webtoonId, serializer);
          sse_encode_String(webtoonTitle, serializer);
          sse_encode_String(chapterUrl, serializer);
          sse_encode_i_32(chapterNumber, serializer);
          sse_encode_String(chapterTitle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cbz_metadata,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloadsDownloadChapterAsCbzConstMeta,
        argValues: [
          basePath,
          webtoonId,
          webtoonTitle,
          chapterUrl,
          chapterNumber,
          chapterTitle,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadsDownloadChapterAsCbzConstMeta =>
      const TaskConstMeta(
        debugName: "download_chapter_as_cbz",
        argNames: [
          "basePath",
          "webtoonId",
          "webtoonTitle",
          "chapterUrl",
          "chapterNumber",
          "chapterTitle",
        ],
      );

  @override
  Future<CbzMetadata> crateApiSimpleDownloadChapterAsCbz({
    required String basePath,
    required String webtoonId,
    required String webtoonTitle,
    required String chapterUrl,
    required int chapterNumber,
    required String chapterTitle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          sse_encode_String(webtoonId, serializer);
          sse_encode_String(webtoonTitle, serializer);
          sse_encode_String(chapterUrl, serializer);
          sse_encode_i_32(chapterNumber, serializer);
          sse_encode_String(chapterTitle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cbz_metadata,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDownloadChapterAsCbzConstMeta,
        argValues: [
          basePath,
          webtoonId,
          webtoonTitle,
          chapterUrl,
          chapterNumber,
          chapterTitle,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDownloadChapterAsCbzConstMeta =>
      const TaskConstMeta(
        debugName: "download_chapter_as_cbz",
        argNames: [
          "basePath",
          "webtoonId",
          "webtoonTitle",
          "chapterUrl",
          "chapterNumber",
          "chapterTitle",
        ],
      );

  @override
  Future<List<Uint8List>> crateApiDownloadsDownloadChapterImages({
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloadsDownloadChapterImagesConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadsDownloadChapterImagesConstMeta =>
      const TaskConstMeta(
        debugName: "download_chapter_images",
        argNames: ["url"],
      );

  @override
  Future<List<Uint8List>> crateApiSimpleDownloadChapterImages({
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDownloadChapterImagesConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDownloadChapterImagesConstMeta =>
      const TaskConstMeta(
        debugName: "download_chapter_images",
        argNames: ["url"],
      );

  @override
  Future<Uint8List> crateApiDownloadsDownloadImage({required String imageUrl}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(imageUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloadsDownloadImageConstMeta,
        argValues: [imageUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadsDownloadImageConstMeta =>
      const TaskConstMeta(debugName: "download_image", argNames: ["imageUrl"]);

  @override
  Future<Uint8List> crateApiSimpleDownloadImage({required String imageUrl}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(imageUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDownloadImageConstMeta,
        argValues: [imageUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDownloadImageConstMeta =>
      const TaskConstMeta(debugName: "download_image", argNames: ["imageUrl"]);

  @override
  Future<List<ChapterPage>> crateApiChaptersGetChapterPages({
    required String chapUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(chapUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chapter_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChaptersGetChapterPagesConstMeta,
        argValues: [chapUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChaptersGetChapterPagesConstMeta =>
      const TaskConstMeta(
        debugName: "get_chapter_pages",
        argNames: ["chapUrl"],
      );

  @override
  Future<List<ChapterPage>> crateApiSimpleGetChapterPages({
    required String chapUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(chapUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chapter_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGetChapterPagesConstMeta,
        argValues: [chapUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetChapterPagesConstMeta =>
      const TaskConstMeta(
        debugName: "get_chapter_pages",
        argNames: ["chapUrl"],
      );

  @override
  Future<LibraryInfo> crateApiLibraryGetLibrary({required String basePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_library_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLibraryGetLibraryConstMeta,
        argValues: [basePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryGetLibraryConstMeta =>
      const TaskConstMeta(debugName: "get_library", argNames: ["basePath"]);

  @override
  Future<LibraryInfo> crateApiSimpleGetLibrary({required String basePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_library_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGetLibraryConstMeta,
        argValues: [basePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetLibraryConstMeta =>
      const TaskConstMeta(debugName: "get_library", argNames: ["basePath"]);

  @override
  Future<List<ApiEpisodeItem>> crateApiEpisodesGetWebtoonEpisodes({
    required String titleNo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(titleNo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_api_episode_item,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiEpisodesGetWebtoonEpisodesConstMeta,
        argValues: [titleNo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEpisodesGetWebtoonEpisodesConstMeta =>
      const TaskConstMeta(
        debugName: "get_webtoon_episodes",
        argNames: ["titleNo"],
      );

  @override
  Future<List<ApiEpisodeItem>> crateApiSimpleGetWebtoonEpisodes({
    required String titleNo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(titleNo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_api_episode_item,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGetWebtoonEpisodesConstMeta,
        argValues: [titleNo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetWebtoonEpisodesConstMeta =>
      const TaskConstMeta(
        debugName: "get_webtoon_episodes",
        argNames: ["titleNo"],
      );

  @override
  Future<WebtoonLibraryItem> crateApiLibraryGetWebtoonLibrary({
    required String basePath,
    required String webtoonId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          sse_encode_String(webtoonId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_webtoon_library_item,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLibraryGetWebtoonLibraryConstMeta,
        argValues: [basePath, webtoonId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryGetWebtoonLibraryConstMeta =>
      const TaskConstMeta(
        debugName: "get_webtoon_library",
        argNames: ["basePath", "webtoonId"],
      );

  @override
  Future<WebtoonLibraryItem> crateApiSimpleGetWebtoonLibrary({
    required String basePath,
    required String webtoonId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          sse_encode_String(webtoonId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_webtoon_library_item,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGetWebtoonLibraryConstMeta,
        argValues: [basePath, webtoonId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetWebtoonLibraryConstMeta =>
      const TaskConstMeta(
        debugName: "get_webtoon_library",
        argNames: ["basePath", "webtoonId"],
      );

  @override
  Future<String> crateApiDownloadsMergeCbzFiles({
    required String basePath,
    required String webtoonId,
    required String webtoonTitle,
    required List<int> chapterNumbers,
    required String outputName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          sse_encode_String(webtoonId, serializer);
          sse_encode_String(webtoonTitle, serializer);
          sse_encode_list_prim_i_32_loose(chapterNumbers, serializer);
          sse_encode_String(outputName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloadsMergeCbzFilesConstMeta,
        argValues: [
          basePath,
          webtoonId,
          webtoonTitle,
          chapterNumbers,
          outputName,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadsMergeCbzFilesConstMeta =>
      const TaskConstMeta(
        debugName: "merge_cbz_files",
        argNames: [
          "basePath",
          "webtoonId",
          "webtoonTitle",
          "chapterNumbers",
          "outputName",
        ],
      );

  @override
  Future<String> crateApiSimpleMergeCbzFiles({
    required String basePath,
    required String webtoonId,
    required String webtoonTitle,
    required List<int> chapterNumbers,
    required String outputName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          sse_encode_String(webtoonId, serializer);
          sse_encode_String(webtoonTitle, serializer);
          sse_encode_list_prim_i_32_loose(chapterNumbers, serializer);
          sse_encode_String(outputName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleMergeCbzFilesConstMeta,
        argValues: [
          basePath,
          webtoonId,
          webtoonTitle,
          chapterNumbers,
          outputName,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMergeCbzFilesConstMeta =>
      const TaskConstMeta(
        debugName: "merge_cbz_files",
        argNames: [
          "basePath",
          "webtoonId",
          "webtoonTitle",
          "chapterNumbers",
          "outputName",
        ],
      );

  @override
  Future<BgDownloadProgress> crateApiDownloadsPollDownloadProgress() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bg_download_progress,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDownloadsPollDownloadProgressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadsPollDownloadProgressConstMeta =>
      const TaskConstMeta(debugName: "poll_download_progress", argNames: []);

  @override
  Future<BgDownloadProgress> crateApiSimplePollDownloadProgress() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bg_download_progress,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimplePollDownloadProgressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePollDownloadProgressConstMeta =>
      const TaskConstMeta(debugName: "poll_download_progress", argNames: []);

  @override
  Future<String> crateApiLibrarySaveWebtoonCover({
    required String basePath,
    required String webtoonId,
    required String coverUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          sse_encode_String(webtoonId, serializer);
          sse_encode_String(coverUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLibrarySaveWebtoonCoverConstMeta,
        argValues: [basePath, webtoonId, coverUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibrarySaveWebtoonCoverConstMeta =>
      const TaskConstMeta(
        debugName: "save_webtoon_cover",
        argNames: ["basePath", "webtoonId", "coverUrl"],
      );

  @override
  Future<String> crateApiSimpleSaveWebtoonCover({
    required String basePath,
    required String webtoonId,
    required String coverUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          sse_encode_String(webtoonId, serializer);
          sse_encode_String(coverUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSaveWebtoonCoverConstMeta,
        argValues: [basePath, webtoonId, coverUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSaveWebtoonCoverConstMeta =>
      const TaskConstMeta(
        debugName: "save_webtoon_cover",
        argNames: ["basePath", "webtoonId", "coverUrl"],
      );

  @override
  Future<List<WebtoonResult>> crateApiSearchSearchWebtoons({
    required String keyword,
    required String langage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(keyword, serializer);
          sse_encode_String(langage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_webtoon_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSearchSearchWebtoonsConstMeta,
        argValues: [keyword, langage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchSearchWebtoonsConstMeta =>
      const TaskConstMeta(
        debugName: "search_webtoons",
        argNames: ["keyword", "langage"],
      );

  @override
  Future<List<WebtoonResult>> crateApiSimpleSearchWebtoons({
    required String keyword,
    required String langage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(keyword, serializer);
          sse_encode_String(langage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_webtoon_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSearchWebtoonsConstMeta,
        argValues: [keyword, langage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSearchWebtoonsConstMeta =>
      const TaskConstMeta(
        debugName: "search_webtoons",
        argNames: ["keyword", "langage"],
      );

  @override
  Future<void> crateApiDownloadsStartBackgroundDownload({
    required String basePath,
    required String webtoonId,
    required String webtoonTitle,
    required List<BgChapterTask> chapters,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          sse_encode_String(webtoonId, serializer);
          sse_encode_String(webtoonTitle, serializer);
          sse_encode_list_bg_chapter_task(chapters, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDownloadsStartBackgroundDownloadConstMeta,
        argValues: [basePath, webtoonId, webtoonTitle, chapters],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDownloadsStartBackgroundDownloadConstMeta =>
      const TaskConstMeta(
        debugName: "start_background_download",
        argNames: ["basePath", "webtoonId", "webtoonTitle", "chapters"],
      );

  @override
  Future<void> crateApiSimpleStartBackgroundDownload({
    required String basePath,
    required String webtoonId,
    required String webtoonTitle,
    required List<BgChapterTask> chapters,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(basePath, serializer);
          sse_encode_String(webtoonId, serializer);
          sse_encode_String(webtoonTitle, serializer);
          sse_encode_list_bg_chapter_task(chapters, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStartBackgroundDownloadConstMeta,
        argValues: [basePath, webtoonId, webtoonTitle, chapters],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStartBackgroundDownloadConstMeta =>
      const TaskConstMeta(
        debugName: "start_background_download",
        argNames: ["basePath", "webtoonId", "webtoonTitle", "chapters"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ApiEpisodeItem dco_decode_api_episode_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ApiEpisodeItem(
      episodeNo: dco_decode_i_32(arr[0]),
      episodeTitle: dco_decode_String(arr[1]),
      thumbnail: dco_decode_String(arr[2]),
      viewerLink: dco_decode_String(arr[3]),
      exposureDateMillis: dco_decode_i_64(arr[4]),
      displayUp: dco_decode_bool(arr[5]),
      hasBgm: dco_decode_bool(arr[6]),
    );
  }

  @protected
  BgChapterTask dco_decode_bg_chapter_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BgChapterTask(
      chapterUrl: dco_decode_String(arr[0]),
      chapterNumber: dco_decode_i_32(arr[1]),
      chapterTitle: dco_decode_String(arr[2]),
    );
  }

  @protected
  BgDownloadProgress dco_decode_bg_download_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return BgDownloadProgress(
      isRunning: dco_decode_bool(arr[0]),
      current: dco_decode_i_32(arr[1]),
      total: dco_decode_i_32(arr[2]),
      currentChapter: dco_decode_i_32(arr[3]),
      currentPage: dco_decode_i_32(arr[4]),
      totalPages: dco_decode_i_32(arr[5]),
      status: dco_decode_String(arr[6]),
      isDone: dco_decode_bool(arr[7]),
      error: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CbzMetadata dco_decode_cbz_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return CbzMetadata(
      webtoonId: dco_decode_String(arr[0]),
      webtoonTitle: dco_decode_String(arr[1]),
      chapterNumber: dco_decode_i_32(arr[2]),
      chapterTitle: dco_decode_String(arr[3]),
      pageCount: dco_decode_i_32(arr[4]),
      fileSize: dco_decode_u_64(arr[5]),
      createdAt: dco_decode_String(arr[6]),
      filePath: dco_decode_String(arr[7]),
    );
  }

  @protected
  ChapterPage dco_decode_chapter_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ChapterPage(
      pageNumber: dco_decode_i_32(arr[0]),
      imageUrl: dco_decode_String(arr[1]),
      width: dco_decode_i_32(arr[2]),
      height: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  LibraryInfo dco_decode_library_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return LibraryInfo(webtoons: dco_decode_list_webtoon_library_item(arr[0]));
  }

  @protected
  List<ApiEpisodeItem> dco_decode_list_api_episode_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_episode_item).toList();
  }

  @protected
  List<BgChapterTask> dco_decode_list_bg_chapter_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bg_chapter_task).toList();
  }

  @protected
  List<CbzMetadata> dco_decode_list_cbz_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_cbz_metadata).toList();
  }

  @protected
  List<ChapterPage> dco_decode_list_chapter_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chapter_page).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<WebtoonLibraryItem> dco_decode_list_webtoon_library_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_webtoon_library_item).toList();
  }

  @protected
  List<WebtoonResult> dco_decode_list_webtoon_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_webtoon_result).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WebtoonLibraryItem dco_decode_webtoon_library_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return WebtoonLibraryItem(
      webtoonId: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      coverPath: dco_decode_String(arr[2]),
      chapters: dco_decode_list_cbz_metadata(arr[3]),
      totalSize: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  WebtoonResult dco_decode_webtoon_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return WebtoonResult(
      titleNo: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      author: dco_decode_String(arr[2]),
      views: dco_decode_String(arr[3]),
      url: dco_decode_String(arr[4]),
      coverUrl: dco_decode_String(arr[5]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ApiEpisodeItem sse_decode_api_episode_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_episodeNo = sse_decode_i_32(deserializer);
    var var_episodeTitle = sse_decode_String(deserializer);
    var var_thumbnail = sse_decode_String(deserializer);
    var var_viewerLink = sse_decode_String(deserializer);
    var var_exposureDateMillis = sse_decode_i_64(deserializer);
    var var_displayUp = sse_decode_bool(deserializer);
    var var_hasBgm = sse_decode_bool(deserializer);
    return ApiEpisodeItem(
      episodeNo: var_episodeNo,
      episodeTitle: var_episodeTitle,
      thumbnail: var_thumbnail,
      viewerLink: var_viewerLink,
      exposureDateMillis: var_exposureDateMillis,
      displayUp: var_displayUp,
      hasBgm: var_hasBgm,
    );
  }

  @protected
  BgChapterTask sse_decode_bg_chapter_task(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapterUrl = sse_decode_String(deserializer);
    var var_chapterNumber = sse_decode_i_32(deserializer);
    var var_chapterTitle = sse_decode_String(deserializer);
    return BgChapterTask(
      chapterUrl: var_chapterUrl,
      chapterNumber: var_chapterNumber,
      chapterTitle: var_chapterTitle,
    );
  }

  @protected
  BgDownloadProgress sse_decode_bg_download_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isRunning = sse_decode_bool(deserializer);
    var var_current = sse_decode_i_32(deserializer);
    var var_total = sse_decode_i_32(deserializer);
    var var_currentChapter = sse_decode_i_32(deserializer);
    var var_currentPage = sse_decode_i_32(deserializer);
    var var_totalPages = sse_decode_i_32(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_isDone = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return BgDownloadProgress(
      isRunning: var_isRunning,
      current: var_current,
      total: var_total,
      currentChapter: var_currentChapter,
      currentPage: var_currentPage,
      totalPages: var_totalPages,
      status: var_status,
      isDone: var_isDone,
      error: var_error,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CbzMetadata sse_decode_cbz_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_webtoonId = sse_decode_String(deserializer);
    var var_webtoonTitle = sse_decode_String(deserializer);
    var var_chapterNumber = sse_decode_i_32(deserializer);
    var var_chapterTitle = sse_decode_String(deserializer);
    var var_pageCount = sse_decode_i_32(deserializer);
    var var_fileSize = sse_decode_u_64(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    return CbzMetadata(
      webtoonId: var_webtoonId,
      webtoonTitle: var_webtoonTitle,
      chapterNumber: var_chapterNumber,
      chapterTitle: var_chapterTitle,
      pageCount: var_pageCount,
      fileSize: var_fileSize,
      createdAt: var_createdAt,
      filePath: var_filePath,
    );
  }

  @protected
  ChapterPage sse_decode_chapter_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pageNumber = sse_decode_i_32(deserializer);
    var var_imageUrl = sse_decode_String(deserializer);
    var var_width = sse_decode_i_32(deserializer);
    var var_height = sse_decode_i_32(deserializer);
    return ChapterPage(
      pageNumber: var_pageNumber,
      imageUrl: var_imageUrl,
      width: var_width,
      height: var_height,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  LibraryInfo sse_decode_library_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_webtoons = sse_decode_list_webtoon_library_item(deserializer);
    return LibraryInfo(webtoons: var_webtoons);
  }

  @protected
  List<ApiEpisodeItem> sse_decode_list_api_episode_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiEpisodeItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_episode_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<BgChapterTask> sse_decode_list_bg_chapter_task(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BgChapterTask>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bg_chapter_task(deserializer));
    }
    return ans_;
  }

  @protected
  List<CbzMetadata> sse_decode_list_cbz_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CbzMetadata>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_cbz_metadata(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChapterPage> sse_decode_list_chapter_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChapterPage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chapter_page(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<WebtoonLibraryItem> sse_decode_list_webtoon_library_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WebtoonLibraryItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_webtoon_library_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<WebtoonResult> sse_decode_list_webtoon_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WebtoonResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_webtoon_result(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WebtoonLibraryItem sse_decode_webtoon_library_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_webtoonId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_coverPath = sse_decode_String(deserializer);
    var var_chapters = sse_decode_list_cbz_metadata(deserializer);
    var var_totalSize = sse_decode_u_64(deserializer);
    return WebtoonLibraryItem(
      webtoonId: var_webtoonId,
      title: var_title,
      coverPath: var_coverPath,
      chapters: var_chapters,
      totalSize: var_totalSize,
    );
  }

  @protected
  WebtoonResult sse_decode_webtoon_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_titleNo = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    var var_views = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_coverUrl = sse_decode_String(deserializer);
    return WebtoonResult(
      titleNo: var_titleNo,
      title: var_title,
      author: var_author,
      views: var_views,
      url: var_url,
      coverUrl: var_coverUrl,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_api_episode_item(
    ApiEpisodeItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.episodeNo, serializer);
    sse_encode_String(self.episodeTitle, serializer);
    sse_encode_String(self.thumbnail, serializer);
    sse_encode_String(self.viewerLink, serializer);
    sse_encode_i_64(self.exposureDateMillis, serializer);
    sse_encode_bool(self.displayUp, serializer);
    sse_encode_bool(self.hasBgm, serializer);
  }

  @protected
  void sse_encode_bg_chapter_task(
    BgChapterTask self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.chapterUrl, serializer);
    sse_encode_i_32(self.chapterNumber, serializer);
    sse_encode_String(self.chapterTitle, serializer);
  }

  @protected
  void sse_encode_bg_download_progress(
    BgDownloadProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isRunning, serializer);
    sse_encode_i_32(self.current, serializer);
    sse_encode_i_32(self.total, serializer);
    sse_encode_i_32(self.currentChapter, serializer);
    sse_encode_i_32(self.currentPage, serializer);
    sse_encode_i_32(self.totalPages, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_bool(self.isDone, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_cbz_metadata(CbzMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.webtoonId, serializer);
    sse_encode_String(self.webtoonTitle, serializer);
    sse_encode_i_32(self.chapterNumber, serializer);
    sse_encode_String(self.chapterTitle, serializer);
    sse_encode_i_32(self.pageCount, serializer);
    sse_encode_u_64(self.fileSize, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.filePath, serializer);
  }

  @protected
  void sse_encode_chapter_page(ChapterPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.pageNumber, serializer);
    sse_encode_String(self.imageUrl, serializer);
    sse_encode_i_32(self.width, serializer);
    sse_encode_i_32(self.height, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_library_info(LibraryInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_webtoon_library_item(self.webtoons, serializer);
  }

  @protected
  void sse_encode_list_api_episode_item(
    List<ApiEpisodeItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_episode_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bg_chapter_task(
    List<BgChapterTask> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bg_chapter_task(item, serializer);
    }
  }

  @protected
  void sse_encode_list_cbz_metadata(
    List<CbzMetadata> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_cbz_metadata(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chapter_page(
    List<ChapterPage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chapter_page(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_32_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(
      self is Int32List ? self : Int32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_webtoon_library_item(
    List<WebtoonLibraryItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_webtoon_library_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_webtoon_result(
    List<WebtoonResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_webtoon_result(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_webtoon_library_item(
    WebtoonLibraryItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.webtoonId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.coverPath, serializer);
    sse_encode_list_cbz_metadata(self.chapters, serializer);
    sse_encode_u_64(self.totalSize, serializer);
  }

  @protected
  void sse_encode_webtoon_result(WebtoonResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.titleNo, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.author, serializer);
    sse_encode_String(self.views, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.coverUrl, serializer);
  }
}
