// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `detect_image_extension`, `update_library_index`

Future<Uint8List> downloadImage({required String imageUrl}) =>
    RustLib.instance.api.crateApiDownloadsDownloadImage(imageUrl: imageUrl);

Future<List<Uint8List>> downloadChapterImages({required String url}) =>
    RustLib.instance.api.crateApiDownloadsDownloadChapterImages(url: url);

Future<CbzMetadata> downloadChapterAsCbz({
  required String basePath,
  required String webtoonId,
  required String webtoonTitle,
  required String chapterUrl,
  required int chapterNumber,
  required String chapterTitle,
}) => RustLib.instance.api.crateApiDownloadsDownloadChapterAsCbz(
  basePath: basePath,
  webtoonId: webtoonId,
  webtoonTitle: webtoonTitle,
  chapterUrl: chapterUrl,
  chapterNumber: chapterNumber,
  chapterTitle: chapterTitle,
);

Future<String> mergeCbzFiles({
  required String basePath,
  required String webtoonId,
  required String webtoonTitle,
  required List<int> chapterNumbers,
  required String outputName,
}) => RustLib.instance.api.crateApiDownloadsMergeCbzFiles(
  basePath: basePath,
  webtoonId: webtoonId,
  webtoonTitle: webtoonTitle,
  chapterNumbers: chapterNumbers,
  outputName: outputName,
);
