// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<LibraryInfo> getLibrary({required String basePath}) =>
    RustLib.instance.api.crateApiLibraryGetLibrary(basePath: basePath);

Future<WebtoonLibraryItem> getWebtoonLibrary({
  required String basePath,
  required String webtoonId,
}) => RustLib.instance.api.crateApiLibraryGetWebtoonLibrary(
  basePath: basePath,
  webtoonId: webtoonId,
);

Future<String> saveWebtoonCover({
  required String basePath,
  required String webtoonId,
  required String coverUrl,
}) => RustLib.instance.api.crateApiLibrarySaveWebtoonCover(
  basePath: basePath,
  webtoonId: webtoonId,
  coverUrl: coverUrl,
);
