// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cbz_path`, `cover_path`, `new`, `webtoon_dir`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StoragePaths`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class ApiEpisodeItem {
  final int episodeNo;
  final String episodeTitle;
  final String thumbnail;
  final String viewerLink;
  final PlatformInt64 exposureDateMillis;
  final bool displayUp;
  final bool hasBgm;

  const ApiEpisodeItem({
    required this.episodeNo,
    required this.episodeTitle,
    required this.thumbnail,
    required this.viewerLink,
    required this.exposureDateMillis,
    required this.displayUp,
    required this.hasBgm,
  });

  @override
  int get hashCode =>
      episodeNo.hashCode ^
      episodeTitle.hashCode ^
      thumbnail.hashCode ^
      viewerLink.hashCode ^
      exposureDateMillis.hashCode ^
      displayUp.hashCode ^
      hasBgm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiEpisodeItem &&
          runtimeType == other.runtimeType &&
          episodeNo == other.episodeNo &&
          episodeTitle == other.episodeTitle &&
          thumbnail == other.thumbnail &&
          viewerLink == other.viewerLink &&
          exposureDateMillis == other.exposureDateMillis &&
          displayUp == other.displayUp &&
          hasBgm == other.hasBgm;
}

class CbzMetadata {
  final String webtoonId;
  final String webtoonTitle;
  final int chapterNumber;
  final String chapterTitle;
  final int pageCount;
  final BigInt fileSize;
  final String createdAt;
  final String filePath;

  const CbzMetadata({
    required this.webtoonId,
    required this.webtoonTitle,
    required this.chapterNumber,
    required this.chapterTitle,
    required this.pageCount,
    required this.fileSize,
    required this.createdAt,
    required this.filePath,
  });

  @override
  int get hashCode =>
      webtoonId.hashCode ^
      webtoonTitle.hashCode ^
      chapterNumber.hashCode ^
      chapterTitle.hashCode ^
      pageCount.hashCode ^
      fileSize.hashCode ^
      createdAt.hashCode ^
      filePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CbzMetadata &&
          runtimeType == other.runtimeType &&
          webtoonId == other.webtoonId &&
          webtoonTitle == other.webtoonTitle &&
          chapterNumber == other.chapterNumber &&
          chapterTitle == other.chapterTitle &&
          pageCount == other.pageCount &&
          fileSize == other.fileSize &&
          createdAt == other.createdAt &&
          filePath == other.filePath;
}

class ChapterPage {
  final int pageNumber;
  final String imageUrl;
  final int width;
  final int height;

  const ChapterPage({
    required this.pageNumber,
    required this.imageUrl,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      pageNumber.hashCode ^
      imageUrl.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterPage &&
          runtimeType == other.runtimeType &&
          pageNumber == other.pageNumber &&
          imageUrl == other.imageUrl &&
          width == other.width &&
          height == other.height;
}

class LibraryInfo {
  final List<WebtoonLibraryItem> webtoons;

  const LibraryInfo({required this.webtoons});

  @override
  int get hashCode => webtoons.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryInfo &&
          runtimeType == other.runtimeType &&
          webtoons == other.webtoons;
}

class WebtoonLibraryItem {
  final String webtoonId;
  final String title;
  final String coverPath;
  final List<CbzMetadata> chapters;
  final BigInt totalSize;

  const WebtoonLibraryItem({
    required this.webtoonId,
    required this.title,
    required this.coverPath,
    required this.chapters,
    required this.totalSize,
  });

  @override
  int get hashCode =>
      webtoonId.hashCode ^
      title.hashCode ^
      coverPath.hashCode ^
      chapters.hashCode ^
      totalSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebtoonLibraryItem &&
          runtimeType == other.runtimeType &&
          webtoonId == other.webtoonId &&
          title == other.title &&
          coverPath == other.coverPath &&
          chapters == other.chapters &&
          totalSize == other.totalSize;
}

class WebtoonResult {
  final String titleNo;
  final String title;
  final String author;
  final String views;
  final String url;
  final String coverUrl;

  const WebtoonResult({
    required this.titleNo,
    required this.title,
    required this.author,
    required this.views,
    required this.url,
    required this.coverUrl,
  });

  @override
  int get hashCode =>
      titleNo.hashCode ^
      title.hashCode ^
      author.hashCode ^
      views.hashCode ^
      url.hashCode ^
      coverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebtoonResult &&
          runtimeType == other.runtimeType &&
          titleNo == other.titleNo &&
          title == other.title &&
          author == other.author &&
          views == other.views &&
          url == other.url &&
          coverUrl == other.coverUrl;
}
