// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<WebtoonResult>> searchWebtoons({
  required String keyword,
  required String langage,
}) => RustLib.instance.api.crateApiSimpleSearchWebtoons(
  keyword: keyword,
  langage: langage,
);

Future<List<ApiEpisodeItem>> getWebtoonEpisodes({required String titleNo}) =>
    RustLib.instance.api.crateApiSimpleGetWebtoonEpisodes(titleNo: titleNo);

Future<List<ChapterPage>> getChapterPages({required String chapUrl}) =>
    RustLib.instance.api.crateApiSimpleGetChapterPages(chapUrl: chapUrl);

Future<Uint8List> downloadImage({required String imageUrl}) =>
    RustLib.instance.api.crateApiSimpleDownloadImage(imageUrl: imageUrl);

Future<List<Uint8List>> downloadChapterImages({required String url}) =>
    RustLib.instance.api.crateApiSimpleDownloadChapterImages(url: url);

Future<CbzMetadata> downloadChapterAsCbz({
  required String basePath,
  required String webtoonId,
  required String webtoonTitle,
  required String chapterUrl,
  required int chapterNumber,
  required String chapterTitle,
}) => RustLib.instance.api.crateApiSimpleDownloadChapterAsCbz(
  basePath: basePath,
  webtoonId: webtoonId,
  webtoonTitle: webtoonTitle,
  chapterUrl: chapterUrl,
  chapterNumber: chapterNumber,
  chapterTitle: chapterTitle,
);

Future<LibraryInfo> getLibrary({required String basePath}) =>
    RustLib.instance.api.crateApiSimpleGetLibrary(basePath: basePath);

Future<WebtoonLibraryItem> getWebtoonLibrary({
  required String basePath,
  required String webtoonId,
}) => RustLib.instance.api.crateApiSimpleGetWebtoonLibrary(
  basePath: basePath,
  webtoonId: webtoonId,
);

Future<String> saveWebtoonCover({
  required String basePath,
  required String webtoonId,
  required String coverUrl,
}) => RustLib.instance.api.crateApiSimpleSaveWebtoonCover(
  basePath: basePath,
  webtoonId: webtoonId,
  coverUrl: coverUrl,
);

Future<String> mergeCbzFiles({
  required String basePath,
  required String webtoonId,
  required String webtoonTitle,
  required List<int> chapterNumbers,
  required String outputName,
}) => RustLib.instance.api.crateApiSimpleMergeCbzFiles(
  basePath: basePath,
  webtoonId: webtoonId,
  webtoonTitle: webtoonTitle,
  chapterNumbers: chapterNumbers,
  outputName: outputName,
);
