// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Recherche des webtoons sur Webtoons.com par scraping HTML
Future<List<WebtoonResult>> searchWebtoons({required String keyword}) =>
    RustLib.instance.api.crateApiSimpleSearchWebtoons(keyword: keyword);

class WebtoonResult {
  final String title;
  final String author;
  final String views;
  final String url;
  final String coverUrl;

  const WebtoonResult({
    required this.title,
    required this.author,
    required this.views,
    required this.url,
    required this.coverUrl,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      author.hashCode ^
      views.hashCode ^
      url.hashCode ^
      coverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebtoonResult &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          author == other.author &&
          views == other.views &&
          url == other.url &&
          coverUrl == other.coverUrl;
}
